
ALTER  TABLE  회원
    DROP  PRIMARY  KEY  CASCADE;
ALTER  TABLE  개인인력
    DROP  PRIMARY  KEY  CASCADE;
ALTER  TABLE  도매업자
    DROP  PRIMARY  KEY  CASCADE;
ALTER  TABLE  취급작물
    DROP  PRIMARY  KEY  CASCADE;
ALTER  TABLE  인력소
    DROP  PRIMARY  KEY  CASCADE;
ALTER  TABLE  장비
    DROP  PRIMARY  KEY  CASCADE;
ALTER  TABLE  장비업체
    DROP  PRIMARY  KEY  CASCADE;
ALTER  TABLE  작물
    DROP  PRIMARY  KEY  CASCADE;
ALTER  TABLE  지역
    DROP  PRIMARY  KEY  CASCADE;
ALTER  TABLE  온라인강의
    DROP  PRIMARY  KEY  CASCADE;
ALTER  TABLE  정부지원
    DROP  PRIMARY  KEY  CASCADE;
ALTER  TABLE  수혜자격
    DROP  PRIMARY  KEY  CASCADE;
ALTER  TABLE  멘토
    DROP  PRIMARY  KEY  CASCADE;
ALTER  TABLE  재배작물
    DROP  PRIMARY  KEY  CASCADE;

DROP TABLE 회원; 
DROP TABLE 개인인력; 
DROP TABLE 도매업자; 
DROP TABLE 취급작물; 
DROP TABLE 인력소;
DROP TABLE 장비;
DROP TABLE 장비업체;
DROP TABLE 작물;
DROP TABLE 지역;
DROP TABLE 온라인강의;
DROP TABLE 정부지원;
DROP TABLE 수혜자격; 
DROP TABLE 멘토; 
DROP TABLE 재배작물;

DROP TABLE 대여하다;
DROP TABLE 보유하다;
DROP TABLE 인력소_계약하다;
DROP TABLE 도매업자_계약하다;
DROP TABLE 소속되다;
DROP TABLE 추천하다;
DROP TABLE 판매하다;
DROP TABLE 특화하다;
DROP TABLE 선택하다;
DROP TABLE 수강하다;
DROP TABLE 지원하다;
DROP TABLE 지도받다;